<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\ResumeForge.Application\ResumeForge.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="QuestPDF" />
  </ItemGroup>
</Project>
