using System.Net;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Logging;
using ResumeForge.Application.Abstractions;

namespace ResumeForge.Infrastructure.Ai;

/// <summary>
/// <see cref="ILanguageModel"/> backed by any endpoint speaking OpenAI's chat-completions
/// wire format — the <c>deepseek</c>, <c>openai</c>, and <c>lmstudio</c> presets, and any
/// other OpenAI-compatible endpoint an unlisted provider is configured against
/// (CONTRACTS.md §8). One client serves them all because the split that matters is wire
/// format, not vendor.
///
/// Structured output degrades through three strategies — forced tool call, then
/// <c>json_schema</c> response format, then prompted JSON — probed once per process and
/// remembered in <see cref="StructuredOutputStrategyMemo"/> thereafter. Independently of
/// the strategy, a response that fails to deserialize into the caller's requested type is
/// treated as a schema-validation failure and retried once on the same strategy, feeding
/// the error back to the model.
/// </summary>
public sealed class OpenAiCompatibleLanguageModel(
    IHttpClientFactory httpClientFactory,
    AiOptions options,
    JsonSchemaRegistry schemaRegistry,
    StructuredOutputStrategyMemo strategyMemo,
    ILogger<OpenAiCompatibleLanguageModel> logger) : ILanguageModel
{
    /// <summary>The name registered for this model's <see cref="IHttpClientFactory"/> client.</summary>
    public const string HttpClientName = "openai-compatible";

    private const string ToolName = "emit_result";
    private const int MaxAttempts = 2;

    private static readonly JsonSerializerOptions SerializerOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.CamelCase) },
    };

    /// <inheritdoc />
    /// <remarks>
    /// Carries both provider and model (e.g. <c>lmstudio/qwen3-8b</c>), per CONTRACTS.md
    /// §8, so <see cref="CachingLanguageModel"/> never serves a cached response generated by
    /// a different provider or model.
    /// </remarks>
    public string ModelId => $"{options.Provider}/{options.Model}";

    /// <inheritdoc />
    public async Task<ModelResponse<T>> CompleteAsync<T>(ModelRequest request, CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(request);

        var schema = schemaRegistry.GetSchema(request.SchemaName);
        var client = httpClientFactory.CreateClient(HttpClientName);
        var apiKey = string.IsNullOrWhiteSpace(options.ApiKey) ? null : options.ApiKey;

        var pinned = ParsePinnedStrategy(options.StructuredOutput);
        var strategy = pinned ?? strategyMemo.Resolved ?? StructuredOutputStrategy.ForcedToolCall;

        string? validationError = null;
        Exception? lastFailure = null;
        var totalUsage = TokenUsage.Empty;
        var attempt = 0;

        while (true)
        {
            OpenAiChatResult result;
            try
            {
                result = await SendAsync(client, apiKey, options.Model, strategy, request, schema, validationError, ct).ConfigureAwait(false);
            }
            catch (StructuredOutputStrategyRejectedException rejection) when (pinned is null && Next(strategy) is { } next)
            {
                logger.LogInformation(
                    "Provider '{Provider}' rejected structured-output strategy {Strategy}, falling back to {Next}: {Reason}",
                    options.Provider, strategy, next, rejection.Message);
                strategy = next;
                validationError = null;
                attempt = 0;
                continue;
            }

            // The strategy succeeded at the protocol level (a tool call came back, or the
            // provider accepted the response_format), regardless of whether the content
            // ultimately deserializes — remember it so the next call skips straight here.
            strategyMemo.Remember(strategy);
            totalUsage += result.Usage;
            attempt++;

            try
            {
                var payloadJson = UnwrapPayload(result.ResultJson, request.SchemaName, schemaRegistry);
                var value = JsonSerializer.Deserialize<T>(payloadJson, SerializerOptions)
                    ?? throw new JsonException("Model response deserialized to null.");

                return new ModelResponse<T> { Value = value, Usage = totalUsage, FromCache = false };
            }
            catch (JsonException ex)
            {
                lastFailure = ex;
                validationError = ex.Message;
                logger.LogWarning(
                    "Model response for schema '{SchemaName}' failed validation on attempt {Attempt}/{MaxAttempts}: {Error}",
                    request.SchemaName, attempt, MaxAttempts, ex.Message);

                if (attempt >= MaxAttempts)
                {
                    // Well-formed-but-non-conforming JSON, twice in a row, is a strategy
                    // problem, not a one-off hiccup: a forced tool call the provider half-
                    // supports (e.g. ignoring part of the schema) is likelier to be
                    // constrained correctly by json_schema, and json_schema likelier still by
                    // prompted JSON. Fall through exactly as a protocol-level rejection would,
                    // unless the strategy was explicitly pinned — then this must still throw.
                    if (pinned is null && Next(strategy) is { } next)
                    {
                        logger.LogInformation(
                            "Provider '{Provider}' returned well-formed-but-non-conforming JSON for schema '{SchemaName}' on " +
                            "structured-output strategy {Strategy} after {MaxAttempts} attempt(s), falling back to {Next}.",
                            options.Provider, request.SchemaName, strategy, MaxAttempts, next);
                        strategy = next;
                        validationError = null;
                        attempt = 0;
                        continue;
                    }

                    throw new InvalidOperationException(
                        $"Model response for schema '{request.SchemaName}' failed schema validation after {MaxAttempts} attempt(s).", lastFailure);
                }
            }
        }
    }

    private static StructuredOutputStrategy? ParsePinnedStrategy(string configured) => configured.Trim().ToLowerInvariant() switch
    {
        "auto" => null,
        "tool" => StructuredOutputStrategy.ForcedToolCall,
        "json_schema" => StructuredOutputStrategy.JsonSchema,
        "prompted" => StructuredOutputStrategy.PromptedJson,
        _ => throw new InvalidOperationException(
            $"Unknown ResumeForge:Ai:StructuredOutput '{configured}'. Expected 'auto', 'tool', 'json_schema', or 'prompted'."),
    };

    private static StructuredOutputStrategy? Next(StructuredOutputStrategy strategy) => strategy switch
    {
        StructuredOutputStrategy.ForcedToolCall => StructuredOutputStrategy.JsonSchema,
        StructuredOutputStrategy.JsonSchema => StructuredOutputStrategy.PromptedJson,
        _ => null,
    };

    /// <summary>
    /// Unwraps <paramref name="resultJson"/>'s schema-declared payload property (see
    /// <see cref="JsonSchemaRegistry.GetPayloadPropertyName"/>) before the caller deserializes
    /// into its requested <c>T</c>. Every structured-output strategy — forced tool call,
    /// <c>json_schema</c>, and prompted JSON alike — sends the model the same object-wrapped
    /// schema, so all three need this same unwrap. A response that isn't the expected object
    /// shape is surfaced as a <see cref="JsonException"/>, exactly like any other schema-
    /// validation failure, so it flows through the same retry/fallback machinery.
    /// </summary>
    private static string UnwrapPayload(string resultJson, string schemaName, JsonSchemaRegistry schemaRegistry)
    {
        var payloadProperty = schemaRegistry.GetPayloadPropertyName(schemaName);

        using var doc = JsonDocument.Parse(resultJson);
        if (doc.RootElement.ValueKind != JsonValueKind.Object || !doc.RootElement.TryGetProperty(payloadProperty, out var payload))
        {
            throw new JsonException(
                $"Model response for schema '{schemaName}' was not an object carrying a '{payloadProperty}' property.");
        }

        return payload.GetRawText();
    }

    private static async Task<OpenAiChatResult> SendAsync(
        HttpClient client, string? apiKey, string model, StructuredOutputStrategy strategy,
        ModelRequest request, JsonElement schema, string? previousError, CancellationToken ct)
    {
        var systemContent = strategy == StructuredOutputStrategy.PromptedJson
            ? $"{request.System}\n\nRespond with ONLY a single JSON object satisfying this JSON Schema exactly, with no other text, no markdown fences:\n{schema.GetRawText()}"
            : request.System;

        var userContent = previousError is null
            ? request.User
            : $"{request.User}\n\nYour previous response failed schema validation: {previousError}\nRespond again with corrected output that satisfies the schema exactly.";

        var payload = new JsonObject
        {
            ["model"] = model,
            ["max_tokens"] = request.MaxOutputTokens,
            ["temperature"] = request.Temperature,
            ["messages"] = new JsonArray(
                new JsonObject { ["role"] = "system", ["content"] = systemContent },
                new JsonObject { ["role"] = "user", ["content"] = userContent }),
        };

        switch (strategy)
        {
            case StructuredOutputStrategy.ForcedToolCall:
                payload["tools"] = new JsonArray(new JsonObject
                {
                    ["type"] = "function",
                    ["function"] = new JsonObject
                    {
                        ["name"] = ToolName,
                        ["description"] = $"Emits the '{request.SchemaName}' result as validated structured data.",
                        ["parameters"] = JsonNode.Parse(schema.GetRawText()),
                    },
                });
                payload["tool_choice"] = new JsonObject
                {
                    ["type"] = "function",
                    ["function"] = new JsonObject { ["name"] = ToolName },
                };
                break;

            case StructuredOutputStrategy.JsonSchema:
                payload["response_format"] = new JsonObject
                {
                    ["type"] = "json_schema",
                    ["json_schema"] = new JsonObject
                    {
                        ["name"] = ToolName,
                        ["schema"] = JsonNode.Parse(schema.GetRawText()),
                        ["strict"] = true,
                    },
                };
                break;

            case StructuredOutputStrategy.PromptedJson:
                payload["response_format"] = new JsonObject { ["type"] = "json_object" };
                break;
        }

        using var httpRequest = new HttpRequestMessage(HttpMethod.Post, "chat/completions")
        {
            Content = new StringContent(payload.ToJsonString(), Encoding.UTF8, "application/json"),
        };
        if (apiKey is not null)
        {
            httpRequest.Headers.Authorization = new AuthenticationHeaderValue("Bearer", apiKey);
        }

        using var response = await client.SendAsync(httpRequest, ct).ConfigureAwait(false);
        var responseBody = await response.Content.ReadAsStringAsync(ct).ConfigureAwait(false);

        if (response.StatusCode == HttpStatusCode.BadRequest)
        {
            throw new StructuredOutputStrategyRejectedException(strategy, responseBody);
        }

        if (!response.IsSuccessStatusCode)
        {
            throw new OpenAiApiException((int)response.StatusCode, responseBody);
        }

        using var doc = JsonDocument.Parse(responseBody);
        var root = doc.RootElement;
        var usage = ParseUsage(root);

        if (strategy == StructuredOutputStrategy.ForcedToolCall)
        {
            var arguments = ExtractToolCallArguments(root);
            if (arguments is null)
            {
                // HTTP 200 carrying no tool call — e.g. deepseek-reasoner, which does not
                // support forced function calls (CONTRACTS.md §8). Reject the strategy so
                // the caller falls through to the next one.
                throw new StructuredOutputStrategyRejectedException(strategy, responseBody);
            }

            return new OpenAiChatResult(arguments, usage);
        }

        var content = ExtractMessageContent(root)
            ?? throw new InvalidOperationException("OpenAI-compatible response had no message content.");
        return new OpenAiChatResult(content, usage);
    }

    private static string? ExtractToolCallArguments(JsonElement root)
    {
        if (!TryGetFirstChoiceMessage(root, out var message) ||
            !message.TryGetProperty("tool_calls", out var toolCalls) ||
            toolCalls.ValueKind != JsonValueKind.Array)
        {
            return null;
        }

        foreach (var call in toolCalls.EnumerateArray())
        {
            if (call.TryGetProperty("function", out var function) &&
                function.TryGetProperty("name", out var nameEl) &&
                nameEl.GetString() == ToolName &&
                function.TryGetProperty("arguments", out var argumentsEl) &&
                argumentsEl.ValueKind == JsonValueKind.String)
            {
                return argumentsEl.GetString();
            }
        }

        return null;
    }

    private static string? ExtractMessageContent(JsonElement root)
    {
        if (!TryGetFirstChoiceMessage(root, out var message) ||
            !message.TryGetProperty("content", out var contentEl) ||
            contentEl.ValueKind != JsonValueKind.String)
        {
            return null;
        }

        return contentEl.GetString();
    }

    private static bool TryGetFirstChoiceMessage(JsonElement root, out JsonElement message)
    {
        if (root.TryGetProperty("choices", out var choices) &&
            choices.ValueKind == JsonValueKind.Array &&
            choices.GetArrayLength() > 0 &&
            choices[0].TryGetProperty("message", out message))
        {
            return true;
        }

        message = default;
        return false;
    }

    /// <summary>
    /// Maps <c>usage.prompt_tokens</c>/<c>usage.completion_tokens</c>, with a server-side
    /// context-cache hit — DeepSeek's <c>usage.prompt_cache_hit_tokens</c>, OpenAI's
    /// <c>usage.prompt_tokens_details.cached_tokens</c> — onto
    /// <see cref="TokenUsage.CacheHits"/>, per CONTRACTS.md §8.
    /// </summary>
    private static TokenUsage ParseUsage(JsonElement root)
    {
        if (!root.TryGetProperty("usage", out var usageEl))
        {
            return new TokenUsage { InputTokens = 0, OutputTokens = 0, ModelCalls = 1, CacheHits = 0 };
        }

        var cacheHits = 0;
        if (usageEl.TryGetProperty("prompt_cache_hit_tokens", out var deepSeekHits))
        {
            cacheHits = deepSeekHits.GetInt32();
        }
        else if (usageEl.TryGetProperty("prompt_tokens_details", out var details) &&
                 details.TryGetProperty("cached_tokens", out var openAiHits))
        {
            cacheHits = openAiHits.GetInt32();
        }

        return new TokenUsage
        {
            InputTokens = usageEl.TryGetProperty("prompt_tokens", out var pt) ? pt.GetInt32() : 0,
            OutputTokens = usageEl.TryGetProperty("completion_tokens", out var comp) ? comp.GetInt32() : 0,
            ModelCalls = 1,
            CacheHits = cacheHits,
        };
    }

    private sealed record OpenAiChatResult(string ResultJson, TokenUsage Usage);

    /// <summary>
    /// Signals that the provider rejected <see cref="Strategy"/> at the protocol level (an
    /// HTTP 400, or a 200 carrying no tool call for <see cref="StructuredOutputStrategy.ForcedToolCall"/>)
    /// so the caller should fall through to the next strategy in the ladder.
    /// </summary>
    private sealed class StructuredOutputStrategyRejectedException(StructuredOutputStrategy strategy, string responseBody)
        : Exception($"Strategy {strategy} was rejected: {(responseBody.Length > 300 ? responseBody[..300] : responseBody)}")
    {
        public StructuredOutputStrategy Strategy { get; } = strategy;
    }
}
